core/urls.py
from django.urls import path
from .views import inicio, registrarme, nosotros, productos
from .views import usuarios, bodega, ventas, boleta, ingresar, usuarios
from .views import misdatos, miscompras, salir, carrito, ficha
from .views import cambiar_estado_boleta, poblar, obtener_productos, eliminar_producto_en_bodega
from .views import premio, eliminar_producto_en_carrito, agregar_producto_al_carrito
from .views import vaciar_carrito, mipassword, cambiar_password, comprar_ahora

urlpatterns = [
    path('', inicio, name='inicio'),
    path('inicio', inicio, name='inicio'),
    path('registrarme', registrarme, name='registrarme'),
    path('nosotros', nosotros, name='nosotros'),
    path('productos/<accion>/<id>', productos, name='productos'),
    path('usuarios/<accion>/<id>', usuarios, name='usuarios'),
    path('cambiar_password', cambiar_password, name='cambiar_password'),
    path('bodega', bodega, name='bodega'),
    path('obtener_productos', obtener_productos, name='obtener_productos'),
    path('eliminar_producto_en_bodega/<bodega_id>', eliminar_producto_en_bodega, name='eliminar_producto_en_bodega'),
    path('ventas', ventas, name='ventas'),
    path('boleta/<nro_boleta>', boleta, name='boleta'),
    path('cambiar_estado_boleta/<nro_boleta>/<estado>', cambiar_estado_boleta, name='cambiar_estado_boleta'),
    path('ingresar', ingresar, name='ingresar'),
    path('misdatos', misdatos, name='misdatos'),
    path('mipassword', mipassword, name='mipassword'),
    path('miscompras', miscompras, name='miscompras'),
    path('salir', salir, name='salir'),
    path('carrito', carrito, name='carrito'),
    path('eliminar_producto_en_carrito/<carrito_id>', eliminar_producto_en_carrito, name='eliminar_producto_en_carrito'),
    path('vaciar_carrito', vaciar_carrito, name='vaciar_carrito'),
    path('agregar_producto_al_carrito/<producto_id>', agregar_producto_al_carrito, name='agregar_producto_al_carrito'),
    path('ficha/<producto_id>', ficha, name='ficha'),
    path('comprar_ahora', comprar_ahora, name='comprar_ahora'),
    path('premio', premio, name='premio'),
    path('poblar', poblar, name='poblar'),
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    #path('api/', include('apirest.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from core.templatetags.custom_filters import formatear_dinero
from django.db import models
from django.db.models import Min
from django.db import connection

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False, verbose_name='Nombre categoría')
    
    class Meta:
        db_table = 'Categoria'
        verbose_name = "Categoría de producto"
        verbose_name_plural = "Categorías de productos"
        ordering = ['nombre']
    
    def __str__(self):
        return f'{self.nombre}'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar la Categoría',
            'accion_actualizar': 'actualizar la Categoría'
        }

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, verbose_name='Categoría')
    nombre = models.CharField(max_length=100, blank=False, null=False, verbose_name='Nombre producto')
    descripcion = models.CharField(max_length=800, blank=False, null=False, verbose_name='Descripción')
    precio = models.IntegerField(blank=False, null=False, verbose_name='Precio')
    descuento_subscriptor = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='% Descuento subscriptor'
    )
    descuento_oferta = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='% Descuento oferta'
    )
    imagen = models.ImageField(upload_to='productos/', blank=False, null=False, verbose_name='Imagen')
    
    class Meta:
        db_table = 'Producto'
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['categoria', 'nombre']

    def __str__(self):
        return f'{self.nombre} (ID {self.id})'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el Producto',
            'accion_actualizar': 'actualizar el Producto'
        }

class Perfil(models.Model):
    USUARIO_CHOICES = [
        ('Cliente', 'Cliente'),
        ('Administrador', 'Administrador'),
        ('Superusuario', 'Superusuario'),
    ]
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_usuario = models.CharField(
        choices=USUARIO_CHOICES,
        max_length=50,
        blank=False,
        null=False,
        verbose_name='Tipo de usuario'
    )
    rut = models.CharField(max_length=15, blank=False, null=False, verbose_name='RUT')
    direccion = models.CharField(max_length=800, blank=False, null=False, verbose_name='Dirección')
    subscrito = models.BooleanField(blank=False, null=False, verbose_name='Subscrito')
    imagen = models.ImageField(upload_to='perfiles/', blank=False, null=False, verbose_name='Imagen')
    
    class Meta:
        db_table = 'Perfil'
        verbose_name = "Perfil de usuario"
        verbose_name_plural = "Perfiles de usuarios"
        ordering = ['tipo_usuario']

    def __str__(self):
        subscrito = ''
        if self.tipo_usuario == 'Cliente':
            subscrito = ' subscrito' if self.subscrito else ' no subscrito'
        return f'{self.usuario.first_name} {self.usuario.last_name} (ID {self.id} - {self.tipo_usuario}{subscrito})'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el Perfil',
            'accion_actualizar': 'actualizar el Perfil'
        }

class Carrito(models.Model):
    cliente = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    precio = models.IntegerField(blank=False, null=False, verbose_name='Precio')
    descuento_subscriptor = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto subs'
    )
    descuento_oferta = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto oferta'
    )
    descuento_total = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto total'
    )
    descuentos = models.IntegerField(blank=False, null=False, verbose_name='Descuentos')
    precio_a_pagar = models.IntegerField(blank=False, null=False, verbose_name='Precio a pagar')
    
    class Meta:
        db_table = 'Carrito'
        verbose_name = "Carrito de compras"
        verbose_name_plural = "Carritos de compras"
        ordering = ['cliente', 'producto']

    def __str__(self):
        return f'{self.id} Carrito de {self.cliente.usuario.first_name} {self.cliente.usuario.last_name} (Producto {self.producto.categoria.nombre} - {self.producto.nombre} - {formatear_dinero(self.precio)})'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el Carrito',
            'accion_actualizar': 'actualizar el Carrito'
        }

class Boleta(models.Model):
    ESTADO_CHOICES = [
        ('Anulado', 'Anulado'),
        ('Vendido', 'Vendido'),
        ('Despachado', 'Despachado'),
        ('Entregado', 'Entregado'),
    ]
    nro_boleta = models.IntegerField(primary_key=True, blank=False, null=False, verbose_name='Nro boleta')
    cliente = models.ForeignKey(Perfil, on_delete=models.DO_NOTHING)
    monto_sin_iva = models.IntegerField(blank=False, null=False, verbose_name='Monto sin IVA')
    iva = models.IntegerField(blank=False, null=False, verbose_name='IVA')
    total_a_pagar = models.IntegerField(blank=False, null=False, verbose_name='Total a pagar')
    fecha_venta = models.DateField(blank=False, null=False, verbose_name='Fecha de venta')
    fecha_despacho = models.DateField(blank=True, null=True, verbose_name='Fecha de despacho')
    fecha_entrega = models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')
    estado = models.CharField(choices=ESTADO_CHOICES, max_length=50, blank=False, null=False, verbose_name='Estado')
    
    class Meta:
        db_table = 'Boleta'
        verbose_name = "Boleta"
        verbose_name_plural = "Boletas"

    def __str__(self):
        return f'Boleta {self.nro_boleta} de {self.cliente.usuario.first_name} {self.cliente.usuario.last_name} por {formatear_dinero(self.total_a_pagar)}'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar la Boleta',
            'accion_actualizar': 'actualizar la Boleta'
        }

class Bodega(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING, verbose_name='Producto')

    class Meta:
        db_table = 'Bodega'
        verbose_name = "Bodega"
        verbose_name_plural = "Bodegas"

    def __str__(self):
        consulta_sql = f'SELECT boleta_id FROM DetalleBoleta WHERE bodega_id={self.id}'
        with connection.cursor() as cursor:
            cursor.execute(consulta_sql)
            resultado = cursor.fetchone()
        info = f'Vendido (Boleta {resultado[0]})' if resultado else 'En bodega'
        return f'{self.producto.nombre} (ID {self.id}) - {info}'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el producto de la Bodega',
            'accion_actualizar': 'actualizar el producto de la Bodega'
        }

class DetalleBoleta(models.Model):
    boleta = models.ForeignKey(Boleta, on_delete=models.DO_NOTHING)
    bodega = models.ForeignKey(Bodega, on_delete=models.DO_NOTHING)
    precio = models.IntegerField(blank=False, null=False, verbose_name='Precio')
    descuento_subscriptor = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto subs'
    )
    descuento_oferta = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto oferta'
    )
    descuento_total = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        blank=False,
        null=False,
        verbose_name='Descto total'
    )
    descuentos = models.IntegerField(blank=False, null=False, verbose_name='Descuentos')
    precio_a_pagar = models.IntegerField(blank=False, null=False, verbose_name='Precio a pagar')
    
    class Meta:
        db_table = 'DetalleBoleta'
        verbose_name = "Detalle de boleta"
        verbose_name_plural = "Detalles de boletas"

    def __str__(self):
        minimo_id = DetalleBoleta.objects.filter(boleta_id=self.boleta.nro_boleta).aggregate(minimo_id=Min('id'))['minimo_id']
        nro_item = self.id - minimo_id + 1
        return f'Boleta {self.boleta.nro_boleta} Item {nro_item} {self.bodega.producto.nombre} - {formatear_dinero(self.precio_a_pagar)}'
    
    def acciones():
        return {
            'accion_eliminar': 'eliminar el Detalle de la Boleta',
            'accion_actualizar': 'actualizar el Detalle de la Boleta'
        }

core/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Categoria, Producto, Perfil

# *********************************************************************************************************#
#                                                                                                          #
# INSTRUCCIONES PARA EL ALUMNO, PUEDES SEGUIR EL VIDEO TUTORIAL, COMPLETAR EL CODIGO E INCORPORAR EL TUYO: #
#                                                                                                          #
# https://drive.google.com/drive/folders/1ObwMnpKmCXVbq3SMwJKlSRE0PCn0buk8?usp=drive_link                  #
#                                                                                                          #
# *********************************************************************************************************#

# LA PAGINA MANTENEDOR DE PRODUCTOS:
class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = [
            'categoria',
            'nombre',
            'descripcion',
            'precio',
            'descuento_subscriptor',
            'descuento_oferta',
            'imagen',
        ]
        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 4}),
            'imagen': forms.FileInput(attrs={'style': 'display:none;'}),
        }
        labels = {
            'nombre': 'Nombre',
            'descuento_subscriptor': 'Subscriptor(%)',
            'descuento_oferta': 'Oferta(%)',
        }

# El formulario de bodega está listo, no necesitas modificarlo
class BodegaForm(Form):
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), label='Categoría')
    producto = forms.ModelChoiceField(queryset=Producto.objects.none(), label='Producto')
    cantidad = forms.IntegerField(label='Cantidad')
    class Meta:
        fields = '__all__'

# El formulario de ingreso está listo, no necesitas modificarlo
class IngresarForm(Form):
    username = forms.CharField(widget=forms.TextInput(), label="Cuenta")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")
    class Meta:
        fields = ['username', 'password']

# LA PAGINA DE REGISTRO DE NUEVO CLIENTE:
class RegistroUsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        labels = {
            'email': 'E-mail',
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(RegistroUsuarioForm, self).__init__(*args, **kwargs)
    
    def clean(self):
        cleaned_data = super().clean()
        contraseña = cleaned_data.get("password1")
        contraseña2 = cleaned_data.get("password2")

        if contraseña and contraseña2 and contraseña != contraseña2:
            self.add_error('password2', "Las contraseñas no coinciden")

        return cleaned_data


# LA PAGINA DE REGISTRO DE NUEVO CLIENTE Y MIS DATOS:
class RegistroPerfilForm(ModelForm):

    class Meta:
        model = Perfil
        fields = ('rut','direccion','imagen', 'subscrito')
        exclude = ('tipo_usuario',)
        widgets = {
            'direccion': forms.Textarea(attrs={'rows': 3}),
            'imagen': forms.FileInput(attrs={'style': 'displaynone;'}),
        }
        labels = {
            'rut': 'RUT',
            'direccion': 'Direccion',
            'imagen': 'Foto',
            'subscrito': 'Suscribirse'
        }
# LA PAGINA MIS DATOS Y MANTENEDOR DE USUARIOS:
class UsuarioForm(ModelForm):
   class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        labels = {
            'email': 'E-mail',
        }


# LA PAGINA MANTENEDOR DE USUARIOS:
class PerfilForm(ModelForm):
    class Meta:
        model = Perfil
        fields = ('tipo_usuario', 'rut', 'direccion', 'subscrito', 'imagen')
        widgets = {
            'direccion': forms.Textarea(attrs={'rows': 2}),
            'imagen': forms.FileInput(attrs={'style': 'displaynone;'}),
        }

core/templates/core/bodega.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
  
  <div class="container">
    <div class="card">
      <div class="card-body">
        <form id="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <h1 class="titulo-mantenedor"> Mantenedor de Bodega </h1>
          <div class="row">
            <div class="col-md-8">
              <div class="mb-3">
                {{ form|as_bootstrap_form }}
              </div>
            </div>
            <div class="col-md-4">
              <div class="text-center mb-2">
                {% if form.imagen.value %}
                  <img id="cuadro-imagen" src="/media/{{ form.imagen.value }}" class="img-thumbnail me-3"
                       style="width: 250px; height: auto; object-fit: cover; background-color: #1A1A1A;">
                {% else %}
                  <img id="cuadro-imagen" src="{% static 'core/img/sin-imagen.png' %}" class="img-thumbnail me-3"
                       style="width: 250px; height: auto; object-fit: cover; background-color: #1A1A1A;">
                {% endif %}
              </div>
            </div>
          </div>

          <div class="mt-2 mb-3 text-center">
            <button type="submit" class="btn btn-primary btn-md"> Agregar </button>
            <button type="reset" class="btn btn-primary btn-md" onclick="document.getElementById('cuadro-imagen').src='{% static 'core/img/sin-imagen.png' %}';"> Nuevo </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% if productos %}
    <div class="container mt-5">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title" style="color: black;"> Lista de Productos </h1>

          <table id="tabla-principal" class="table">
            <thead>
              <tr>
                <th style="text-align: center;"> ID </th>
                <th style="text-align: center;"> Categoría </th>
                <th style="text-align: center;"> Producto </th>
                <th style="text-align: center;"> Estado </th>
                <th style="text-align: center;"> Imagen </th>
                <th style="text-align: center;"> Acción </th>
              </tr>
            </thead>
            <tbody>
              {% for producto in productos %}
                <tr>
                  <td>{{ producto.bodega_id }}</td>
                  <td>{{ producto.nombre_categoria }}</td>
                  <td>{{ producto.nombre_producto }}</td>
                  <td>{{ producto.estado }}</td>
                  <td style="text-align: center;">
                    <img src="/media/{{ producto.imagen }}" class="img-thumbnail btn-design2" style="max-height: 75px;"\>
                  </td>
                  <td style="text-align: center;">
                    {% if producto.estado == 'En bodega' %}
                      <a href="{% url 'eliminar_producto_en_bodega' producto.bodega_id %}" class="btn btn-danger btn-sm btn-design1" style="font-style: normal;"> Eliminar </a>
                    {% else %}
                      <a href="{% url 'eliminar_producto_en_bodega' producto.bodega_id %}" class="btn btn-secondary btn-sm btn-design1 disabled" style="font-style: normal;"> Eliminar </a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}

{% block script %}
  <input type="hidden" id="url_obtener_productos" value="{% url 'obtener_productos' %}">
  <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
  <script src="{% static 'core/js/bodega.js' %}"></script>
  <script src="{% static 'core/css/bodega.css' %}"></script>
  <link rel="stylesheet" href="{% static 'core/css/bodega.css' %}">
  <script>
    $(document).ready(function() {
      $('#tabla-principal').DataTable({
        "language": {
          "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        }
      });
      
      // Escuchar cambios en el input de imagen
      $('#id_imagen').change(function(evt) {
        const file = evt.target.files[0];
        const reader = new FileReader();
        reader.onload = function(e) {
          $('#cuadro-imagen').attr('src', e.target.result);
        };
        reader.readAsDataURL(file);
      });
    });
  </script>
{% endblock script %}

core/templates/core/ficha.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="container d-flex justify-content-center mt-5">
    <div class="text-center mb-4">
        <h2>{{ nombre }}</h2>
    </div>
</div>
<div class="container d-flex justify-content-center">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <form method="post" id="formulario-ficha">
                {% csrf_token %}

                <div class="mb-3 text-center">
                    <img src="{{ imagen.url }}" alt="Imagen del producto" class="img-fluid mb-3">
                    <h5 class="card-title">{{ nombre }}</h5>
                    <p class="card-text">{{ html_estado|safe }}</p>
                    <p class="card-text">{{ html_precio|safe }}</p>
                    <p class="card-text">{{ descripcion }}</p>
                    <p class="card-text">{{ html_stock|safe }}</p>
                </div>

                <div class="d-flex justify-content-around mt-4">
                    <input type="hidden" id="accion">
                    <a href="{% url 'comprar_ahora' %}" class="btn btn-primary ancho-160px">Comprar ahora</a>
                    <a href="{% url 'agregar_producto_al_carrito' id %}" class="btn btn-secondary ancho-160px">Agregar al carrito</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    <script src="{% static 'core/js/ficha.js' %}"></script>
{% endblock script %}

core/templates/core/productos.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card border-1 shadow-lg">
        <div class="card-body">
          <div class="text-center mb-4">
            <h2>Mantenedor de Producto</h2>
          </div>
          <div class="row">
            <div class="col-md-6">
              <form id="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                  {{ form.categoria|as_bootstrap_field }}
                </div>
                <div class="form-group">
                  {{ form.nombre|as_bootstrap_field }}
                </div>
                <div class="form-group">
                  {{ form.descripcion|as_bootstrap_field }}
                </div>
                <div class="form-group">
                  {{ form.precio|as_bootstrap_field }}
                </div>
                <div class="form-group">
                  {{ form.descuento_subscriptor|as_bootstrap_field }}
                </div>
                <div class="form-group">
                  {{ form.descuento_oferta|as_bootstrap_field }}
                </div>
                <input type="file" id="id_imagen" name="imagen" style="display: none;">
                <div class="form-group text-center">
                  <input class="btn btn-primary mb-2" type="submit" value="Guardar">
                  <a class="btn btn-primary mb-2 ml-2" href="{% url 'productos' 'crear' '0' %}">Nuevo</a>
                  <button class="btn btn-primary mb-2 ml-2" onclick="event.preventDefault(); document.getElementById('id_imagen').click();">Seleccionar imagen</button>
                  {% if form.instance.id %}
                  <a class="btn btn-primary mb-2 ml-2" href="{% url 'productos' 'eliminar' form.instance.id %}">Eliminar</a>
                  {% endif %}
                </div>
              </form>
            </div>
            <div class="col-md-6">
              <div class="mb-3 text-center">
                <h4>Imagen del Producto</h4>
                {% if form.instance.imagen %}
                  <img id="cuadro-imagen" src="/media/{{ form.instance.imagen }}" class="img-thumbnail me-3" style="width: 250px; height: auto; object-fit: cover; background-color: #1A1A1A;">
                {% else %}
                  <img id="cuadro-imagen" src="{% static 'core/img/sin-imagen.png' %}" class="img-thumbnail me-3" style="width: 250px; height: auto; object-fit: cover; background-color: #1A1A1A;">
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card border-1 shadow-lg">
        <div class="card-body">
          <table id="tabla-principal" class="table table-hover">
            <thead>
              <tr>
                <th>ID</th>
                <th>Categoría</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>%Subs</th>
                <th>%Oferta</th>
                <th>Imagen</th>
                <th>Editar</th>
                <th>Eliminar</th>
              </tr>
            </thead>
            <tbody>
              {% for producto in productos %}
                <tr>
                  <td>{{ producto.id }}</td>
                  <td>{{ producto.categoria }}</td>
                  <td>{{ producto.nombre }}</td>
                  <td>{{ producto.descripcion }}</td>
                  <td>{{ producto.precio|formatear_dinero }}</td>
                  <td>{{ producto.descuento_subscriptor|formatear_porcentaje }}</td>
                  <td>{{ producto.descuento_oferta|formatear_porcentaje }}</td>
                  <td>
                    <img src="/media/{{ producto.imagen }}" class="producto-sm" alt="">
                  </td>
                  <td>
                    <a href="{% url 'productos' 'actualizar' producto.id %}" class="btn btn-primary btn-sm">Editar</a>
                  </td>
                  <td>
                    <form method="post" action="{% url 'productos' 'eliminar' producto.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                    </form>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'core/js/jquery.min.js' %}"></script>
<script src="{% static 'core/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'core/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'core/js/productos.js' %}"></script>
<link rel="stylesheet" href="{% static 'core/css/dataTables.bootstrap4.min.css' %}">
<script>
$(document).ready(function() {
  $('#tabla-principal').DataTable();
});

// Previsualizar imagen seleccionada
document.getElementById('id_imagen').onchange = function (evt) {
  const [file] = this.files;
  if (file) {
    const reader = new FileReader();
    reader.onload = function(event) {
      document.getElementById('cuadro-imagen').src = event.target.result;
    };
    reader.readAsDataURL(file);
  }
};
</script>
<link rel="stylesheet" href="{% static 'core/css/productos.css' %}">
{% endblock script %}